version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: greer-ord-app_1
      APP_PORT: 8066
    
  app:
    image: greerso/ord:v0.5.1@sha256:0f1cb90980900ca74f598d22f917e3de038b0ce197cffca8231e851fca078810
    restart: on-failure
    user: "1000:1000"
    volumes:
      - "${APP_BITCOIN_DATA_DIR}:/data/.bitcoin"
      - "${APP_DATA_DIR}/data/ord:/data"
